language: d

d:
  - dmd

install:
  - dub fetch doveralls

script:
  - dub test -b unittest-cov
  - dub run doveralls

test:
  dub test

addons:
  apt:
    packages:
    - libasound2-dev
    - libfluidsynth-dev
